version: '3.8'

services:
  bot:
    build: .
    container_name: void-bot
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge